services:
  app:
    build:
      context: app/
    ports:
      - "80:80"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          target: /var/www/html
          path: app
  db:
    build:
      context: db/
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: db